[versions]
accompanist-coil = "0.12.0"
accompanist-insets = "0.12.0"
activity-compose = "1.7.2"
androidx-junit = "1.1.5"
arrow-core = "1.0.1"
clarity = "1.3.0"
converter-moshi = "2.9.0"
core-ktx = "1.10.1"
datastore-preferences = "1.0.0"
espresso-core = "3.5.1"
exoplayer = "2.15.0"
fastble = "2.4.0"
glide = "4.12.0"
google-material = "1.9.0"
gson = "2.9.0"
hilt-android = "2.46.1"
hilt-navigation-compose = "1.0.0"
junit = "4.13.2"
kluent-android = "1.68"
kotlinx-coroutines-test = "1.6.4"
lifecycle-runtime-ktx = "2.6.1"
logging-interceptor = "4.9.2"
material = "1.4.3"
mockk = "1.12.4"
mockwebserver = "4.9.3"
moshi = "1.15.0"
navigation-compose = "2.7.0-beta01"
okhttp3-idling-resource = "1.0.0"
retrofit = "2.9.0"
robolectric = "4.8.1"
room-runtime = "2.5.1"
rssparser = "4.0.2"
runtime = "1.4.3"
turbine = "0.12.3"
ui = "1.4.3"
ui-test-manifest = "1.5.0-beta02"

[libraries]
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist-coil" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist-insets" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow-core" }
clarity = { module = "com.microsoft.clarity:clarity", version.ref = "clarity" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converter-moshi" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
extension-mediasession = { module = "com.google.android.exoplayer:extension-mediasession", version.ref = "exoplayer" }
fastble = { module = "com.github.Jasonchenlijian:FastBle", version.ref = "fastble" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-android" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
junit = { module = "junit:junit", version.ref = "junit" }
kluent = { module = "org.amshove.kluent:kluent", version.ref = "kluent-android" }
kluent-android = { module = "org.amshove.kluent:kluent-android", version.ref = "kluent-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
material = { module = "androidx.compose.material:material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
okhttp3-idling-resource = { module = "com.jakewharton.espresso:okhttp3-idling-resource", version.ref = "okhttp3-idling-resource" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
rssparser = { module = "com.prof18.rssparser:rssparser", version.ref = "rssparser" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }

[plugins]
